# Generated by Django 5.2.17 on 2026-08-27 09:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('image', models.FileField(blank=True, null=True, upload_to='barbers/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'آرایشگر',
                'verbose_name_plural': 'آرایشگرها',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bale_user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='شناسه کاربر بله')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'کاربر ربات',
                'verbose_name_plural': 'کاربران ربات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=150, verbose_name='نام آرایشگاه')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('working_hours_text', models.TextField(blank=True, verbose_name='ساعات کاری')),
                ('location_url', models.URLField(blank=True, verbose_name='لینک لوکیشن')),
                ('reservation_days_ahead', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد روزهای قابل رزرو آینده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'تنظیمات آرایشگاه',
                'verbose_name_plural': 'تنظیمات آرایشگاه',
            },
        ),
        migrations.CreateModel(
            name='BarberWorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'دوشنبه'), (2, 'سه شنبه'), (3, 'چهارشنبه'), (4, 'پنجشنبه'), (5, 'جمعه'), (6, 'شنبه'), (7, 'یکشنبه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت هر نوبت به دقیقه')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='شروع استراحت')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='پایان استراحت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedules', to='appointments.barber', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'برنامه کاری آرایشگر',
                'verbose_name_plural': 'برنامه کاری آرایشگرها',
                'ordering': ['barber', 'day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('barber', 'day_of_week'), name='unique_barber_schedule_per_weekday'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end'), models.CheckConstraint(condition=models.Q(models.Q(('break_end_time__isnull', True), ('break_start_time__isnull', True)), ('break_start_time__lt', models.F('break_end_time')), _connector='OR'), name='schedule_break_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_full_day', models.BooleanField(default=False, verbose_name='کل روز بسته است؟')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('barber', models.ForeignKey(blank=True, help_text='اگر خالی باشد، زمان برای کل آرایشگاه بسته می شود.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='appointments.barber', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'زمان مسدود شده',
                'verbose_name_plural': 'زمان های مسدود شده',
                'ordering': ['date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_full_day', True), models.Q(('end_time__isnull', False), ('start_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='blocked_time_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('status', models.CharField(choices=[('booked', 'رزرو شده'), ('cancelled_by_user', 'لغو شده توسط کاربر'), ('cancelled_by_admin', 'لغو شده توسط ادمین'), ('completed', 'انجام شده'), ('no_show', 'عدم مراجعه')], default='booked', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.barber', verbose_name='آرایشگر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.botuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'status'], name='appointment_date_32174a_idx'), models.Index(fields=['barber', 'date'], name='appointment_barber__eadd5b_idx'), models.Index(fields=['user', 'date'], name='appointment_user_id_7093d3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('barber', 'date', 'start_time'), name='unique_booked_appointment_slot')],
            },
        ),
    ]
