# Generated by Django 5.2.17 on 2026-08-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('waiting_for_first_name', 'Waiting for first name'), ('waiting_for_last_name', 'Waiting for last name'), ('waiting_for_phone', 'Waiting for phone')], default='idle', max_length=50, verbose_name='وضعیت گفتگو')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده موقت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='appointments.botuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت گفتگوی ربات',
                'verbose_name_plural': 'وضعیت گفتگوهای ربات',
            },
        ),
    ]
