# Generated by Django 5.2.17 on 2026-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_botconversationstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting_for_first_name', 'Waiting for first name'), ('waiting_for_last_name', 'Waiting for last name'), ('waiting_for_phone', 'Waiting for phone'), ('waiting_for_barber', 'Waiting for barber'), ('waiting_for_date', 'Waiting for date'), ('waiting_for_time', 'Waiting for time'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('waiting_for_cancel_appointment', 'Waiting for cancel appointment'), ('waiting_for_cancel_confirmation', 'Waiting for cancel confirmation')], default='idle', max_length=50, verbose_name='وضعیت گفتگو'),
        ),
    ]
