# Generated by Django 5.2.17 on 2026-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_botconversationstate_state'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='appointment',
            name='unique_booked_appointment_slot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('barber', 'date', 'start_time'), name='unique_booked_appointment_slot', violation_error_message='این ساعت برای آرایشگر انتخاب\u200cشده قبلاً رزرو شده است.'),
        ),
        migrations.AlterConstraint(
            model_name='barberworkingschedule',
            name='unique_barber_schedule_per_weekday',
            constraint=models.UniqueConstraint(fields=('barber', 'day_of_week'), name='unique_barber_schedule_per_weekday', violation_error_message='برای این آرایشگر در این روز قبلاً برنامه کاری ثبت شده است.'),
        ),
        migrations.AlterConstraint(
            model_name='barberworkingschedule',
            name='schedule_start_before_end',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end', violation_error_message='ساعت پایان کار باید بعد از ساعت شروع باشد.'),
        ),
        migrations.AlterConstraint(
            model_name='barberworkingschedule',
            name='schedule_break_start_before_end',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('break_end_time__isnull', True), ('break_start_time__isnull', True)), ('break_start_time__lt', models.F('break_end_time')), _connector='OR'), name='schedule_break_start_before_end', violation_error_message='شروع و پایان استراحت را به ترتیب و با هم وارد کنید.'),
        ),
        migrations.AlterConstraint(
            model_name='blockedtime',
            name='blocked_time_valid_range',
            constraint=models.CheckConstraint(condition=models.Q(('is_full_day', True), models.Q(('end_time__isnull', False), ('start_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='blocked_time_valid_range', violation_error_message='برای بستن بخشی از روز، یک بازه ساعت معتبر وارد کنید.'),
        ),
    ]
