# Generated by Django 5.2.17 on 2026-09-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_persian_validation_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='biography',
            field=models.TextField(blank=True, max_length=2000, verbose_name='معرفی و سوابق'),
        ),
        migrations.AddField(
            model_name='barber',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سال\u200cهای تجربه'),
        ),
        migrations.AddField(
            model_name='barber',
            name='specialty',
            field=models.CharField(blank=True, max_length=160, verbose_name='تخصص\u200cها'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='contact_intro',
            field=models.TextField(blank=True, max_length=1000, verbose_name='متن خوشامد ارتباط با ما'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='salon/', verbose_name='لوگوی آرایشگاه'),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='social_url',
            field=models.URLField(blank=True, verbose_name='لینک شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='botconversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('waiting_for_full_name', 'دریافت نام و نام خانوادگی'), ('waiting_for_barber_profile', 'مشاهده پروفایل آرایشگر'), ('waiting_for_first_name', 'Waiting for first name'), ('waiting_for_last_name', 'Waiting for last name'), ('waiting_for_phone', 'Waiting for phone'), ('waiting_for_barber', 'Waiting for barber'), ('waiting_for_date', 'Waiting for date'), ('waiting_for_time', 'Waiting for time'), ('waiting_for_confirmation', 'Waiting for confirmation'), ('waiting_for_cancel_appointment', 'Waiting for cancel appointment'), ('waiting_for_cancel_confirmation', 'Waiting for cancel confirmation')], default='idle', max_length=50, verbose_name='وضعیت گفتگو'),
        ),
        migrations.CreateModel(
            name='BarberPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='barbers/portfolio/', verbose_name='تصویر نمونه\u200cکار')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='عنوان نمونه\u200cکار')),
                ('caption', models.TextField(blank=True, max_length=1000, verbose_name='توضیحات')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در ربات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='appointments.barber', verbose_name='آرایشگر')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارهای آرایشگران',
                'ordering': ['position', 'id'],
            },
        ),
    ]
